import { CategoryId } from '../../types';
import { RecommendationCandidate } from './types';

export interface StarterCatalogItem {
  canonicalName: string;
  displayName: string;
  nameUrdu: string;
  nameRomanUrdu: string;
  category: CategoryId;
  emoji: string;
  defaultQuantity: string;
  defaultUnit: string;
}

export const STARTER_POPULAR_ESSENTIALS: StarterCatalogItem[] = [
  {
    canonicalName: 'sugar',
    displayName: 'Sugar',
    nameUrdu: 'چینی',
    nameRomanUrdu: 'Cheeni',
    category: 'cooking_essentials',
    emoji: '🍚',
    defaultQuantity: '1',
    defaultUnit: 'kg',
  },
  {
    canonicalName: 'milk',
    displayName: 'Milk',
    nameUrdu: 'دودھ',
    nameRomanUrdu: 'Doodh',
    category: 'dairy',
    emoji: '🥛',
    defaultQuantity: '1',
    defaultUnit: 'litre',
  },
  {
    canonicalName: 'eggs',
    displayName: 'Eggs',
    nameUrdu: 'انڈے',
    nameRomanUrdu: 'Anday',
    category: 'poultry',
    emoji: '🥚',
    defaultQuantity: '1',
    defaultUnit: 'dozen',
  },
  {
    canonicalName: 'potatoes',
    displayName: 'Potatoes',
    nameUrdu: 'آلو',
    nameRomanUrdu: 'Aloo',
    category: 'vegetables',
    emoji: '🥔',
    defaultQuantity: '1',
    defaultUnit: 'kg',
  },
  {
    canonicalName: 'tomatoes',
    displayName: 'Tomatoes',
    nameUrdu: 'ٹماٹر',
    nameRomanUrdu: 'Tamatar',
    category: 'vegetables',
    emoji: '🍅',
    defaultQuantity: '1',
    defaultUnit: 'kg',
  },
  {
    canonicalName: 'rice',
    displayName: 'Rice',
    nameUrdu: 'چاول',
    nameRomanUrdu: 'Chawal',
    category: 'rice',
    emoji: '🍚',
    defaultQuantity: '5',
    defaultUnit: 'kg',
  },
  {
    canonicalName: 'onions',
    displayName: 'Onions',
    nameUrdu: 'پیاز',
    nameRomanUrdu: 'Pyaz',
    category: 'vegetables',
    emoji: '🧅',
    defaultQuantity: '1',
    defaultUnit: 'kg',
  },
  {
    canonicalName: 'cooking_oil',
    displayName: 'Cooking Oil',
    nameUrdu: 'کوکنگ آئل',
    nameRomanUrdu: 'Cooking Oil',
    category: 'cooking_essentials',
    emoji: '🛢️',
    defaultQuantity: '1',
    defaultUnit: 'litre',
  },
  {
    canonicalName: 'flour',
    displayName: 'Atta / Flour',
    nameUrdu: 'آٹا',
    nameRomanUrdu: 'Atta',
    category: 'grains',
    emoji: '🌾',
    defaultQuantity: '5',
    defaultUnit: 'kg',
  },
  {
    canonicalName: 'tea',
    displayName: 'Chai / Tea',
    nameUrdu: 'چائے کی پتی',
    nameRomanUrdu: 'Chai Patti',
    category: 'beverages',
    emoji: '☕',
    defaultQuantity: '1',
    defaultUnit: 'packet',
  },
];

export const CONTEXT_STARTER_ITEMS: Record<string, StarterCatalogItem[]> = {
  bbq: [
    {
      canonicalName: 'chicken',
      displayName: 'Chicken',
      nameUrdu: 'مرغی / چکن',
      nameRomanUrdu: 'Chicken',
      category: 'poultry',
      emoji: '🍗',
      defaultQuantity: '2',
      defaultUnit: 'kg',
    },
    {
      canonicalName: 'charcoal',
      displayName: 'Charcoal / Koyla',
      nameUrdu: 'کوئلہ',
      nameRomanUrdu: 'Koyla',
      category: 'household',
      emoji: '🪵',
      defaultQuantity: '1',
      defaultUnit: 'bag',
    },
    {
      canonicalName: 'tikka_masala',
      displayName: 'Tikka Masala',
      nameUrdu: 'ٹکہ مصالحہ',
      nameRomanUrdu: 'Tikka Masala',
      category: 'spices',
      emoji: '🌶️',
      defaultQuantity: '1',
      defaultUnit: 'packet',
    },
    {
      canonicalName: 'bbq_sauce',
      displayName: 'BBQ Sauce',
      nameUrdu: 'بی بی کیو ساس',
      nameRomanUrdu: 'BBQ Sauce',
      category: 'sauces_condiments',
      emoji: '🥫',
      defaultQuantity: '1',
      defaultUnit: 'bottle',
    },
    {
      canonicalName: 'cold_drink',
      displayName: 'Cold Drinks / Soda',
      nameUrdu: 'کولڈ ڈرنک',
      nameRomanUrdu: 'Cold Drink',
      category: 'beverages',
      emoji: '🥤',
      defaultQuantity: '2',
      defaultUnit: 'litres',
    },
    {
      canonicalName: 'naan',
      displayName: 'Naan / Roti',
      nameUrdu: 'نان',
      nameRomanUrdu: 'Naan',
      category: 'bakery',
      emoji: '🫓',
      defaultQuantity: '6',
      defaultUnit: 'pieces',
    },
  ],
  pharmacy: [
    {
      canonicalName: 'panadol',
      displayName: 'Panadol',
      nameUrdu: 'پیناڈول',
      nameRomanUrdu: 'Panadol',
      category: 'health',
      emoji: '💊',
      defaultQuantity: '1',
      defaultUnit: 'strip',
    },
    {
      canonicalName: 'bandages',
      displayName: 'Bandages / Band-Aid',
      nameUrdu: 'پٹی',
      nameRomanUrdu: 'Patti',
      category: 'health',
      emoji: '🩹',
      defaultQuantity: '1',
      defaultUnit: 'box',
    },
    {
      canonicalName: 'disprin',
      displayName: 'Disprin',
      nameUrdu: 'ڈسپرین',
      nameRomanUrdu: 'Disprin',
      category: 'health',
      emoji: '💊',
      defaultQuantity: '1',
      defaultUnit: 'strip',
    },
    {
      canonicalName: 'cough_syrup',
      displayName: 'Cough Syrup',
      nameUrdu: 'کھانسی کا شربت',
      nameRomanUrdu: 'Khansi Syrup',
      category: 'health',
      emoji: '🧴',
      defaultQuantity: '1',
      defaultUnit: 'bottle',
    },
    {
      canonicalName: 'pain_relief',
      displayName: 'Pain Relief Balm / Spray',
      nameUrdu: 'درد کا بام',
      nameRomanUrdu: 'Pain Balm',
      category: 'health',
      emoji: '🧴',
      defaultQuantity: '1',
      defaultUnit: 'tube',
    },
    {
      canonicalName: 'sanitizer',
      displayName: 'Hand Sanitizer',
      nameUrdu: 'ہینڈ سینیٹائزر',
      nameRomanUrdu: 'Sanitizer',
      category: 'health',
      emoji: '🧴',
      defaultQuantity: '1',
      defaultUnit: 'bottle',
    },
  ],
  fruits_vegetables: [
    {
      canonicalName: 'potatoes',
      displayName: 'Potatoes',
      nameUrdu: 'آلو',
      nameRomanUrdu: 'Aloo',
      category: 'vegetables',
      emoji: '🥔',
      defaultQuantity: '2',
      defaultUnit: 'kg',
    },
    {
      canonicalName: 'tomatoes',
      displayName: 'Tomatoes',
      nameUrdu: 'ٹماٹر',
      nameRomanUrdu: 'Tamatar',
      category: 'vegetables',
      emoji: '🍅',
      defaultQuantity: '1',
      defaultUnit: 'kg',
    },
    {
      canonicalName: 'onions',
      displayName: 'Onions',
      nameUrdu: 'پیاز',
      nameRomanUrdu: 'Pyaz',
      category: 'vegetables',
      emoji: '🧅',
      defaultQuantity: '2',
      defaultUnit: 'kg',
    },
    {
      canonicalName: 'bananas',
      displayName: 'Bananas',
      nameUrdu: 'کیلے',
      nameRomanUrdu: 'Kailay',
      category: 'fruits',
      emoji: '🍌',
      defaultQuantity: '1',
      defaultUnit: 'dozen',
    },
    {
      canonicalName: 'apples',
      displayName: 'Apples',
      nameUrdu: 'سیب',
      nameRomanUrdu: 'Saib',
      category: 'fruits',
      emoji: '🍎',
      defaultQuantity: '1',
      defaultUnit: 'kg',
    },
    {
      canonicalName: 'lemons',
      displayName: 'Lemons',
      nameUrdu: 'لیمو',
      nameRomanUrdu: 'Leemo',
      category: 'vegetables',
      emoji: '🍋',
      defaultQuantity: '250',
      defaultUnit: 'grams',
    },
  ],
  party: [
    {
      canonicalName: 'cold_drink',
      displayName: 'Cold Drinks / Soda',
      nameUrdu: 'کولڈ ڈرنک',
      nameRomanUrdu: 'Cold Drink',
      category: 'beverages',
      emoji: '🥤',
      defaultQuantity: '2',
      defaultUnit: 'litres',
    },
    {
      canonicalName: 'chips',
      displayName: 'Potato Chips',
      nameUrdu: 'چپس',
      nameRomanUrdu: 'Chips',
      category: 'snacks',
      emoji: '🥔',
      defaultQuantity: '2',
      defaultUnit: 'packets',
    },
    {
      canonicalName: 'juices',
      displayName: 'Fruit Juices',
      nameUrdu: 'جوس',
      nameRomanUrdu: 'Juice',
      category: 'beverages',
      emoji: '🧃',
      defaultQuantity: '2',
      defaultUnit: 'litres',
    },
    {
      canonicalName: 'disposable_glasses',
      displayName: 'Disposable Cups & Plates',
      nameUrdu: 'ڈسپوزیبل برتن',
      nameRomanUrdu: 'Disposable Bartan',
      category: 'household',
      emoji: '🥤',
      defaultQuantity: '1',
      defaultUnit: 'pack',
    },
    {
      canonicalName: 'tissues',
      displayName: 'Tissue Box',
      nameUrdu: 'ٹشو باکس',
      nameRomanUrdu: 'Tissue Box',
      category: 'household',
      emoji: '🧻',
      defaultQuantity: '1',
      defaultUnit: 'box',
    },
  ],
  household: [
    {
      canonicalName: 'dish_soap',
      displayName: 'Dishwashing Bar / Liquid',
      nameUrdu: 'برتن دھونے کا صابن',
      nameRomanUrdu: 'Dish Soap',
      category: 'household',
      emoji: '🧼',
      defaultQuantity: '1',
      defaultUnit: 'bar',
    },
    {
      canonicalName: 'laundry_detergent',
      displayName: 'Laundry Detergent',
      nameUrdu: 'سرف / ڈٹرجنٹ',
      nameRomanUrdu: 'Surf',
      category: 'household',
      emoji: '🧺',
      defaultQuantity: '1',
      defaultUnit: 'kg',
    },
    {
      canonicalName: 'tissue_box',
      displayName: 'Tissue Box',
      nameUrdu: 'ٹشو باکس',
      nameRomanUrdu: 'Tissue Box',
      category: 'household',
      emoji: '🧻',
      defaultQuantity: '1',
      defaultUnit: 'box',
    },
    {
      canonicalName: 'hand_wash',
      displayName: 'Hand Wash',
      nameUrdu: 'ہینڈ واش',
      nameRomanUrdu: 'Hand Wash',
      category: 'household',
      emoji: '🧴',
      defaultQuantity: '1',
      defaultUnit: 'bottle',
    },
    {
      canonicalName: 'trash_bags',
      displayName: 'Trash Bags',
      nameUrdu: 'کچرے کے تھیلے',
      nameRomanUrdu: 'Trash Bags',
      category: 'household',
      emoji: '🗑️',
      defaultQuantity: '1',
      defaultUnit: 'roll',
    },
  ],
  monthly_shopping: [
    {
      canonicalName: 'flour',
      displayName: 'Atta / Flour',
      nameUrdu: 'آٹا',
      nameRomanUrdu: 'Atta',
      category: 'grains',
      emoji: '🌾',
      defaultQuantity: '10',
      defaultUnit: 'kg',
    },
    {
      canonicalName: 'rice',
      displayName: 'Basmati Rice',
      nameUrdu: 'چاول',
      nameRomanUrdu: 'Chawal',
      category: 'rice',
      emoji: '🍚',
      defaultQuantity: '5',
      defaultUnit: 'kg',
    },
    {
      canonicalName: 'cooking_oil',
      displayName: 'Cooking Oil / Ghee',
      nameUrdu: 'کوکنگ آئل',
      nameRomanUrdu: 'Cooking Oil',
      category: 'cooking_essentials',
      emoji: '🛢️',
      defaultQuantity: '5',
      defaultUnit: 'litres',
    },
    {
      canonicalName: 'sugar',
      displayName: 'Sugar',
      nameUrdu: 'چینی',
      nameRomanUrdu: 'Cheeni',
      category: 'cooking_essentials',
      emoji: '🍚',
      defaultQuantity: '5',
      defaultUnit: 'kg',
    },
    {
      canonicalName: 'tea',
      displayName: 'Tea / Chai Patti',
      nameUrdu: 'چائے کی پتی',
      nameRomanUrdu: 'Chai Patti',
      category: 'beverages',
      emoji: '☕',
      defaultQuantity: '2',
      defaultUnit: 'packets',
    },
    {
      canonicalName: 'pulses',
      displayName: 'Daal / Lentils',
      nameUrdu: 'دال',
      nameRomanUrdu: 'Daal',
      category: 'pulses',
      emoji: '🍲',
      defaultQuantity: '2',
      defaultUnit: 'kg',
    },
  ],
  weekly_grocery: [
    {
      canonicalName: 'milk',
      displayName: 'Milk',
      nameUrdu: 'دودھ',
      nameRomanUrdu: 'Doodh',
      category: 'dairy',
      emoji: '🥛',
      defaultQuantity: '2',
      defaultUnit: 'litres',
    },
    {
      canonicalName: 'eggs',
      displayName: 'Eggs',
      nameUrdu: 'انڈے',
      nameRomanUrdu: 'Anday',
      category: 'poultry',
      emoji: '🥚',
      defaultQuantity: '1',
      defaultUnit: 'dozen',
    },
    {
      canonicalName: 'bread',
      displayName: 'Bread',
      nameUrdu: 'ڈبل روٹی',
      nameRomanUrdu: 'Double Roti',
      category: 'bakery',
      emoji: '🍞',
      defaultQuantity: '1',
      defaultUnit: 'loaf',
    },
    {
      canonicalName: 'potatoes',
      displayName: 'Potatoes',
      nameUrdu: 'آلو',
      nameRomanUrdu: 'Aloo',
      category: 'vegetables',
      emoji: '🥔',
      defaultQuantity: '2',
      defaultUnit: 'kg',
    },
    {
      canonicalName: 'tomatoes',
      displayName: 'Tomatoes',
      nameUrdu: 'ٹماٹر',
      nameRomanUrdu: 'Tamatar',
      category: 'vegetables',
      emoji: '🍅',
      defaultQuantity: '1',
      defaultUnit: 'kg',
    },
    {
      canonicalName: 'cooking_oil',
      displayName: 'Cooking Oil',
      nameUrdu: 'کوکنگ آئل',
      nameRomanUrdu: 'Cooking Oil',
      category: 'cooking_essentials',
      emoji: '🛢️',
      defaultQuantity: '1',
      defaultUnit: 'litre',
    },
  ],
};

export function getStarterRecommendations(
  limit: number = 4,
  contextId?: string
): RecommendationCandidate[] {
  let sourceItems: StarterCatalogItem[] = [];

  if (contextId && CONTEXT_STARTER_ITEMS[contextId]) {
    sourceItems = [...CONTEXT_STARTER_ITEMS[contextId]];
  }

  // Supplement with general staples if needed to reach limit
  for (const item of STARTER_POPULAR_ESSENTIALS) {
    if (sourceItems.length >= limit) break;
    if (!sourceItems.some((s) => s.canonicalName === item.canonicalName)) {
      sourceItems.push(item);
    }
  }

  const selected = sourceItems.slice(0, limit);

  return selected.map((item) => ({
    profile: {
      id: `starter_${item.canonicalName}`,
      userId: '',
      canonicalName: item.canonicalName,
      displayName: item.displayName,
      nameUrdu: item.nameUrdu,
      nameRomanUrdu: item.nameRomanUrdu,
      category: item.category,
      emoji: item.emoji,
      purchaseCount: 0,
      firstPurchasedAt: new Date().toISOString(),
      lastPurchasedAt: new Date().toISOString(),
      purchaseHistory: [],
      averageIntervalDays: 7,
      intervalStdDevDays: 0,
      purchaseFrequency: 'weekly',
      preferredQuantity: item.defaultQuantity,
      preferredUnit: item.defaultUnit,
      quantityFrequencies: { [item.defaultQuantity]: 1 },
      unitFrequencies: { [item.defaultUnit]: 1 },
      weekdayDistribution: [0, 0, 0, 0, 0, 0, 0],
      dismissalCount: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    canonicalName: item.canonicalName,
    displayName: item.displayName,
    nameUrdu: item.nameUrdu,
    nameRomanUrdu: item.nameRomanUrdu,
    category: item.category,
    emoji: item.emoji,
    suggestedQuantity: item.defaultQuantity,
    suggestedUnit: item.defaultUnit,
    score: 0.5,
    confidence: 0.5,
    isStarterCatalog: true,
    explanation: {
      type: 'popular_starter',
      textKey: 'recommendations.reasons.starter',
      displayReason: contextId && CONTEXT_STARTER_ITEMS[contextId] ? `Essential for ${contextId.replace(/_/g, ' ')}` : 'Popular staple item',
    },
    scoringFactors: {
      frequencyScore: 0.5,
      recencyScore: 0.5,
      intervalScore: 0.5,
      categoryScore: 0.5,
      contextScore: 0.5,
      cycleUrgencyScore: 0.5,
      regularityScore: 0.5,
      coPurchaseScore: 0,
      weekdayScore: 0,
      dismissalPenalty: 1.0,
      confidence: 0.5,
      totalScore: 0.5,
    },
  }));
}
