import { MasterCatalogItem } from '../../types';

const NOW = '2026-09-03T12:00:00.000Z';

export const INITIAL_MASTER_CATALOG: MasterCatalogItem[] = [
  // ==========================================
  // 1. VEGETABLES (سبزیاں)
  // ==========================================
  {
    id: 'veg_potato',
    canonical_name: 'Potato',
    english_name: 'Potato',
    urdu_name: 'آلو',
    roman_urdu_names: ['Aloo', 'Alu', 'Alo', 'Aalu'],
    aliases: [
      'potato', 'potatoes', 'potatos', 'potatoe',
      'aloo', 'alu', 'alo', 'aalu', 'allu', 'aaloo', 'aluu', 'aluw',
      'آلو', 'الو',
    ],
    common_misspellings: ['poteto', 'potatoe', 'potaato', 'allu', 'alo', 'aalu', 'aluu'],
    category_id: 'vegetables',
    subcategory_id: 'veg_roots',
    searchable_terms: ['potato', 'potatoes', 'aloo', 'alu', 'alo', 'aalu', 'آلو', 'الو', 'sabzi'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🥔',
    default_unit: 'kg',
    canonicalName: 'Potato',
    nameUrdu: 'آلو',
    nameRomanUrdu: 'Aloo',
    categoryId: 'vegetables',
    defaultUnit: 'kg',
  },
  {
    id: 'veg_onion',
    canonical_name: 'Onion',
    english_name: 'Onion',
    urdu_name: 'پیاز',
    roman_urdu_names: ['Pyaz', 'Pyaaz', 'Piyaz', 'Piaz'],
    aliases: [
      'onion', 'onions', 'onoin', 'onins',
      'pyaz', 'pyaaz', 'piyaz', 'piaz', 'payaz', 'piaaz', 'pyaas', 'piazz', 'pyazz',
      'پیاز',
    ],
    common_misspellings: ['onoin', 'onins', 'pyaas', 'piaaz', 'pyz', 'piaz'],
    category_id: 'vegetables',
    subcategory_id: 'veg_roots',
    searchable_terms: ['onion', 'onions', 'pyaz', 'pyaaz', 'piyaz', 'piaz', 'پیاز', 'sabzi'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧅',
    default_unit: 'kg',
    canonicalName: 'Onion',
    nameUrdu: 'پیاز',
    nameRomanUrdu: 'Pyaz',
    categoryId: 'vegetables',
    defaultUnit: 'kg',
  },
  {
    id: 'veg_tomato',
    canonical_name: 'Tomato',
    english_name: 'Tomato',
    urdu_name: 'ٹماٹر',
    roman_urdu_names: ['Tamatar', 'Tamaatar', 'Tmatar'],
    aliases: [
      'tomato', 'tomatoes', 'tomatos', 'tomatoe',
      'tamatar', 'tamaatar', 'tmatar', 'tamater', 'tamatr', 'tamattar', 'tmaatr',
      'ٹماٹر', 'تماٹر',
    ],
    common_misspellings: ['tometo', 'tamater', 'tamatr', 'tmaatar'],
    category_id: 'vegetables',
    subcategory_id: 'veg_nightshades',
    searchable_terms: ['tomato', 'tomatoes', 'tamatar', 'tamaatar', 'tmatar', 'ٹماٹر', 'تماٹر'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍅',
    default_unit: 'kg',
    canonicalName: 'Tomato',
    nameUrdu: 'ٹماٹر',
    nameRomanUrdu: 'Tamatar',
    categoryId: 'vegetables',
    defaultUnit: 'kg',
  },
  {
    id: 'veg_green_chili',
    canonical_name: 'Green Chili',
    english_name: 'Green Chili',
    urdu_name: 'ہری مرچ',
    roman_urdu_names: ['Hari Mirch', 'Sabz Mirch', 'Hari Mirchi'],
    aliases: [
      'green chili', 'green chilli', 'green chillies', 'green chilies',
      'hari mirch', 'haree mirch', 'harimirch', 'hari mirchi', 'sabz mirch', 'mirchi',
      'ہری مرچ', 'سبز مرچ', 'مرچ',
    ],
    common_misspellings: ['hari mirche', 'hare mirch', 'harimirch', 'chilli'],
    category_id: 'vegetables',
    subcategory_id: 'veg_nightshades',
    searchable_terms: ['green chili', 'green chilli', 'hari mirch', 'hari mirchi', 'sabz mirch', 'ہری مرچ'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🌶️',
    default_unit: 'pao',
    canonicalName: 'Green Chili',
    nameUrdu: 'ہری مرچ',
    nameRomanUrdu: 'Hari Mirch',
    categoryId: 'vegetables',
    defaultUnit: 'pao',
  },
  {
    id: 'veg_ginger',
    canonical_name: 'Ginger',
    english_name: 'Ginger',
    urdu_name: 'ادرک',
    roman_urdu_names: ['Adrak', 'Aadrak'],
    aliases: [
      'ginger', 'gingr',
      'adrak', 'adrik', 'adruk', 'aadrak', 'adrakh',
      'ادرک',
    ],
    common_misspellings: ['gingr', 'aadrak', 'adrik'],
    category_id: 'vegetables',
    subcategory_id: 'veg_roots',
    searchable_terms: ['ginger', 'adrak', 'aadrak', 'ادرک'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧄',
    default_unit: 'pao',
    canonicalName: 'Ginger',
    nameUrdu: 'ادرک',
    nameRomanUrdu: 'Adrak',
    categoryId: 'vegetables',
    defaultUnit: 'pao',
  },
  {
    id: 'veg_garlic',
    canonical_name: 'Garlic',
    english_name: 'Garlic',
    urdu_name: 'لہسن',
    roman_urdu_names: ['Lehsan', 'Lahsan', 'Lehsun'],
    aliases: [
      'garlic', 'garlick',
      'lehsan', 'lehsun', 'lahsan', 'lahsun', 'lehsen', 'lasun', 'lasan',
      'لہسن',
    ],
    common_misspellings: ['garlick', 'lahsan', 'lasun'],
    category_id: 'vegetables',
    subcategory_id: 'veg_roots',
    searchable_terms: ['garlic', 'lehsan', 'lehsun', 'lahsun', 'لہسن'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧄',
    default_unit: 'pao',
    canonicalName: 'Garlic',
    nameUrdu: 'لہسن',
    nameRomanUrdu: 'Lehsan',
    categoryId: 'vegetables',
    defaultUnit: 'pao',
  },
  {
    id: 'veg_spinach',
    canonical_name: 'Spinach',
    english_name: 'Spinach',
    urdu_name: 'پالک',
    roman_urdu_names: ['Palak', 'Paalak'],
    aliases: [
      'spinach', 'spinich',
      'palak', 'paalak', 'palk',
      'پالک',
    ],
    common_misspellings: ['spinich', 'palk'],
    category_id: 'vegetables',
    subcategory_id: 'veg_leafy',
    searchable_terms: ['spinach', 'palak', 'paalak', 'پالک'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🥬',
    default_unit: 'kg',
    canonicalName: 'Spinach',
    nameUrdu: 'پالک',
    nameRomanUrdu: 'Palak',
    categoryId: 'vegetables',
    defaultUnit: 'kg',
  },
  {
    id: 'veg_coriander',
    canonical_name: 'Coriander (Dhania)',
    english_name: 'Coriander',
    urdu_name: 'دھنیا',
    roman_urdu_names: ['Dhaniya', 'Dhania', 'Hara Dhaniya'],
    aliases: [
      'coriander', 'cilantro', 'fresh coriander',
      'dhaniya', 'dhania', 'hara dhaniya', 'dhania patta',
      'دھنیا', 'ہرا دھنیا',
    ],
    common_misspellings: ['coriandr', 'dhanya'],
    category_id: 'herbs',
    subcategory_id: 'veg_leafy',
    searchable_terms: ['coriander', 'cilantro', 'dhaniya', 'dhania', 'دھنیا', 'ہرا دھنیا'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🌿',
    default_unit: 'bunch',
    canonicalName: 'Coriander (Dhania)',
    nameUrdu: 'دھنیا',
    nameRomanUrdu: 'Dhaniya',
    categoryId: 'herbs',
    defaultUnit: 'bunch',
  },
  {
    id: 'veg_mint',
    canonical_name: 'Mint (Podina)',
    english_name: 'Mint',
    urdu_name: 'پودینہ',
    roman_urdu_names: ['Podina', 'Pudina', 'Podeena'],
    aliases: [
      'mint', 'mint leaves', 'peppermint',
      'podina', 'pudina', 'podeena', 'pudena',
      'پودینہ',
    ],
    common_misspellings: ['pudeena', 'podena'],
    category_id: 'herbs',
    subcategory_id: 'veg_leafy',
    searchable_terms: ['mint', 'podina', 'pudina', 'podeena', 'پودینہ'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🌿',
    default_unit: 'bunch',
    canonicalName: 'Mint (Podina)',
    nameUrdu: 'پودینہ',
    nameRomanUrdu: 'Podina',
    categoryId: 'herbs',
    defaultUnit: 'bunch',
  },
  {
    id: 'veg_lemon',
    canonical_name: 'Lemon',
    english_name: 'Lemon',
    urdu_name: 'لیموں',
    roman_urdu_names: ['Leemu', 'Limu', 'Nimbu', 'Lemon'],
    aliases: [
      'lemon', 'lemons', 'lime', 'limes',
      'leemu', 'limu', 'nimbu', 'neebu', 'leemoo',
      'لیموں', 'لیمو', 'نیبو',
    ],
    common_misspellings: ['limon', 'leemon', 'nimbo'],
    category_id: 'fruits',
    subcategory_id: 'fruit_citrus',
    searchable_terms: ['lemon', 'lemons', 'lime', 'leemu', 'limu', 'nimbu', 'لیموں', 'لیمو'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍋',
    default_unit: 'pao',
    canonicalName: 'Lemon',
    nameUrdu: 'لیموں',
    nameRomanUrdu: 'Leemu',
    categoryId: 'fruits',
    defaultUnit: 'pao',
  },

  // ==========================================
  // 2. FRUITS (پھل)
  // ==========================================
  {
    id: 'fruit_apple',
    canonical_name: 'Apple',
    english_name: 'Apple',
    urdu_name: 'سیب',
    roman_urdu_names: ['Saib', 'Seb', 'Sayb'],
    aliases: [
      'apple', 'apples',
      'saib', 'seb', 'sayb', 'seyb',
      'سیب',
    ],
    common_misspellings: ['appl', 'sayb'],
    category_id: 'fruits',
    subcategory_id: 'fruit_pome',
    searchable_terms: ['apple', 'apples', 'saib', 'seb', 'سیب'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍎',
    default_unit: 'kg',
    canonicalName: 'Apple',
    nameUrdu: 'سیب',
    nameRomanUrdu: 'Saib',
    categoryId: 'fruits',
    defaultUnit: 'kg',
  },
  {
    id: 'fruit_banana',
    canonical_name: 'Banana',
    english_name: 'Banana',
    urdu_name: 'کیلا',
    roman_urdu_names: ['Kela', 'Kayla', 'Keela'],
    aliases: [
      'banana', 'bananas',
      'kela', 'kayla', 'keela', 'kele', 'kaylay',
      'کیلا', 'کیلے',
    ],
    common_misspellings: ['bannana', 'kayla'],
    category_id: 'fruits',
    subcategory_id: 'fruit_tropical',
    searchable_terms: ['banana', 'bananas', 'kela', 'kele', 'کیلا', 'کیلے'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍌',
    default_unit: 'dozen',
    canonicalName: 'Banana',
    nameUrdu: 'کیلا',
    nameRomanUrdu: 'Kela',
    categoryId: 'fruits',
    defaultUnit: 'dozen',
  },
  {
    id: 'fruit_mango',
    canonical_name: 'Mango',
    english_name: 'Mango',
    urdu_name: 'آم',
    roman_urdu_names: ['Aam', 'Am'],
    aliases: [
      'mango', 'mangoes', 'mangos',
      'aam', 'am', 'anwar ratol', 'chaunsa', 'sindhri', 'doseri',
      'آم', 'چونسہ', 'سندھڑی',
    ],
    common_misspellings: ['mangoe', 'aamm'],
    category_id: 'fruits',
    subcategory_id: 'fruit_tropical',
    searchable_terms: ['mango', 'mangoes', 'aam', 'chaunsa', 'آم'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🥭',
    default_unit: 'kg',
    canonicalName: 'Mango',
    nameUrdu: 'آم',
    nameRomanUrdu: 'Aam',
    categoryId: 'fruits',
    defaultUnit: 'kg',
  },
  {
    id: 'fruit_orange',
    canonical_name: 'Orange',
    english_name: 'Orange',
    urdu_name: 'مالٹا',
    roman_urdu_names: ['Malta', 'Kinnow', 'Kino', 'Mausambi'],
    aliases: [
      'orange', 'oranges', 'kinnow', 'kino', 'kinu',
      'malta', 'mausambi', 'mosambi', 'musambi',
      'مالٹا', 'کینو', 'مسمبی',
    ],
    common_misspellings: ['ornage', 'kinnu', 'kinu'],
    category_id: 'fruits',
    subcategory_id: 'fruit_citrus',
    searchable_terms: ['orange', 'oranges', 'malta', 'kinnow', 'kino', 'مالٹا', 'کینو'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍊',
    default_unit: 'dozen',
    canonicalName: 'Orange',
    nameUrdu: 'مالٹا',
    nameRomanUrdu: 'Malta',
    categoryId: 'fruits',
    defaultUnit: 'dozen',
  },
  {
    id: 'fruit_guava',
    canonical_name: 'Guava',
    english_name: 'Guava',
    urdu_name: 'امرود',
    roman_urdu_names: ['Amrood', 'Amrud'],
    aliases: [
      'guava', 'guavas',
      'amrood', 'amrud', 'amroud',
      'امرود',
    ],
    common_misspellings: ['gauva', 'amrod'],
    category_id: 'fruits',
    subcategory_id: 'fruit_tropical',
    searchable_terms: ['guava', 'amrood', 'amrud', 'امرود'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍈',
    default_unit: 'kg',
    canonicalName: 'Guava',
    nameUrdu: 'امرود',
    nameRomanUrdu: 'Amrood',
    categoryId: 'fruits',
    defaultUnit: 'kg',
  },
  {
    id: 'fruit_grapes',
    canonical_name: 'Grapes',
    english_name: 'Grapes',
    urdu_name: 'انگور',
    roman_urdu_names: ['Angoor', 'Angur'],
    aliases: [
      'grapes', 'grape',
      'angoor', 'angur', 'angour',
      'انگور',
    ],
    common_misspellings: ['graps', 'angur'],
    category_id: 'fruits',
    subcategory_id: 'fruit_berries',
    searchable_terms: ['grapes', 'angoor', 'angur', 'انگور'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍇',
    default_unit: 'kg',
    canonicalName: 'Grapes',
    nameUrdu: 'انگور',
    nameRomanUrdu: 'Angoor',
    categoryId: 'fruits',
    defaultUnit: 'kg',
  },
  {
    id: 'fruit_pomegranate',
    canonical_name: 'Pomegranate',
    english_name: 'Pomegranate',
    urdu_name: 'انار',
    roman_urdu_names: ['Anaar', 'Anar'],
    aliases: [
      'pomegranate', 'pomgranate',
      'anaar', 'anar', 'qandhari anar',
      'انار', 'قندھاری انار',
    ],
    common_misspellings: ['pomgranate', 'anar'],
    category_id: 'fruits',
    subcategory_id: 'fruit_berries',
    searchable_terms: ['pomegranate', 'anaar', 'anar', 'انار'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍎',
    default_unit: 'kg',
    canonicalName: 'Pomegranate',
    nameUrdu: 'انار',
    nameRomanUrdu: 'Anaar',
    categoryId: 'fruits',
    defaultUnit: 'kg',
  },

  // ==========================================
  // 3. GROCERY & STAPLES (راشن اور اناج)
  // ==========================================
  {
    id: 'groc_sugar',
    canonical_name: 'Sugar',
    english_name: 'Sugar',
    urdu_name: 'چینی',
    roman_urdu_names: ['Chini', 'Cheeni'],
    aliases: [
      'sugar', 'sugr', 'white sugar', 'refined sugar',
      'cheeni', 'chini', 'cheni', 'shakar', 'shakkar',
      'چینی', 'شکر', 'سفید چینی',
    ],
    common_misspellings: ['sugr', 'cheni', 'cheeni', 'shakar'],
    category_id: 'cooking_essentials',
    subcategory_id: 'groc_sugar_sweeteners',
    searchable_terms: ['sugar', 'cheeni', 'chini', 'shakar', 'چینی', 'شکر'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧂',
    default_unit: 'kg',
    canonicalName: 'Sugar',
    nameUrdu: 'چینی',
    nameRomanUrdu: 'Chini',
    categoryId: 'cooking_essentials',
    defaultUnit: 'kg',
  },
  {
    id: 'groc_flour',
    canonical_name: 'Wheat Flour',
    english_name: 'Wheat Flour',
    urdu_name: 'آٹا',
    roman_urdu_names: ['Atta', 'Aata', 'Chakki Atta'],
    aliases: [
      'flour', 'wheat flour', 'chakki atta', 'white flour',
      'atta', 'aata', 'ata', 'chakki aata', 'gandum ka atta',
      'آٹا', 'چکی کا آٹا', 'گندم کا آٹا',
    ],
    common_misspellings: ['flouer', 'ata', 'aata'],
    category_id: 'grocery',
    subcategory_id: 'groc_flours',
    searchable_terms: ['flour', 'wheat flour', 'atta', 'aata', 'chakki atta', 'آٹا'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🌾',
    default_unit: 'kg',
    canonicalName: 'Wheat Flour',
    nameUrdu: 'آٹا',
    nameRomanUrdu: 'Atta',
    categoryId: 'grocery',
    defaultUnit: 'kg',
  },
  {
    id: 'groc_rice',
    canonical_name: 'Basmati Rice',
    english_name: 'Basmati Rice',
    urdu_name: 'چاول',
    roman_urdu_names: ['Chawal', 'Basmati Chawal', 'Kainat Chawal'],
    aliases: [
      'rice', 'basmati rice', 'sela rice', 'super kernel',
      'chawal', 'chaawal', 'chawul', 'basmati chawal', 'kainat chawal',
      'چاول', 'باس متی چاول', 'سیلا چاول',
    ],
    common_misspellings: ['chaawal', 'chawl'],
    category_id: 'grocery',
    subcategory_id: 'groc_rice',
    searchable_terms: ['rice', 'basmati rice', 'chawal', 'chaawal', 'چاول'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍚',
    default_unit: 'kg',
    canonicalName: 'Basmati Rice',
    nameUrdu: 'چاول',
    nameRomanUrdu: 'Chawal',
    categoryId: 'grocery',
    defaultUnit: 'kg',
  },
  {
    id: 'groc_lentils',
    canonical_name: 'Lentils (Daal)',
    english_name: 'Lentils (Daal)',
    urdu_name: 'دال',
    roman_urdu_names: ['Daal', 'Dal', 'Daal Chana', 'Daal Moong'],
    aliases: [
      'lentils', 'daal', 'dal', 'pulse', 'pulses',
      'daal chana', 'daal moong', 'daal masoor', 'daal mash',
      'دال', 'دال چنا', 'دال مونگ', 'دال مسور', 'دال ماش',
    ],
    common_misspellings: ['daall', 'dall'],
    category_id: 'grocery',
    subcategory_id: 'groc_pulses',
    searchable_terms: ['lentils', 'daal', 'dal', 'daal chana', 'دال'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🥣',
    default_unit: 'kg',
    canonicalName: 'Lentils (Daal)',
    nameUrdu: 'دال',
    nameRomanUrdu: 'Daal',
    categoryId: 'grocery',
    defaultUnit: 'kg',
  },
  {
    id: 'groc_cooking_oil',
    canonical_name: 'Cooking Oil',
    english_name: 'Cooking Oil',
    urdu_name: 'کوکنگ آئل',
    roman_urdu_names: ['Cooking Oil', 'Tail', 'Tel'],
    aliases: [
      'oil', 'cooking oil', 'vegetable oil', 'canola oil', 'sunflower oil',
      'tail', 'tel', 'cooking oil pouch', 'cooking oil bottle',
      'کوکنگ آئل', 'تیل',
    ],
    common_misspellings: ['cookingoil', 'tail', 'oyil'],
    category_id: 'grocery',
    subcategory_id: 'groc_oil_ghee',
    searchable_terms: ['cooking oil', 'oil', 'tail', 'tel', 'کوکنگ آئل', 'تیل'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🛢️',
    default_unit: 'liter',
    canonicalName: 'Cooking Oil',
    nameUrdu: 'کوکنگ آئل',
    nameRomanUrdu: 'Cooking Oil',
    categoryId: 'grocery',
    defaultUnit: 'liter',
  },
  {
    id: 'groc_ghee',
    canonical_name: 'Ghee',
    english_name: 'Ghee',
    urdu_name: 'گھی',
    roman_urdu_names: ['Ghee', 'Banaspati Ghee', 'Desi Ghee'],
    aliases: [
      'ghee', 'banaspati ghee', 'desi ghee', 'dalda ghee',
      'ghi', 'banaspati', 'desi ghi',
      'گھی', 'بناسپتی گھی', 'دیسی گھی',
    ],
    common_misspellings: ['ghey', 'ghi'],
    category_id: 'grocery',
    subcategory_id: 'groc_oil_ghee',
    searchable_terms: ['ghee', 'banaspati ghee', 'desi ghee', 'گھی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧈',
    default_unit: 'kg',
    canonicalName: 'Ghee',
    nameUrdu: 'گھی',
    nameRomanUrdu: 'Ghee',
    categoryId: 'grocery',
    defaultUnit: 'kg',
  },
  {
    id: 'groc_salt',
    canonical_name: 'Salt',
    english_name: 'Salt',
    urdu_name: 'نمک',
    roman_urdu_names: ['Namak', 'National Namak'],
    aliases: [
      'salt', 'table salt', 'iodized salt', 'white salt', 'pink salt',
      'namak', 'nimak', 'lahori namak',
      'نمک', 'سفید نمک', 'لاہوری نمک',
    ],
    common_misspellings: ['namk', 'nimak'],
    category_id: 'cooking_essentials',
    subcategory_id: 'groc_salts',
    searchable_terms: ['salt', 'namak', 'نمک'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧂',
    default_unit: 'packet',
    canonicalName: 'Salt',
    nameUrdu: 'نمک',
    nameRomanUrdu: 'Namak',
    categoryId: 'cooking_essentials',
    defaultUnit: 'packet',
  },
  {
    id: 'groc_tea',
    canonical_name: 'Tea (Chai Patti)',
    english_name: 'Tea (Chai Patti)',
    urdu_name: 'چائے کی پتی',
    roman_urdu_names: ['Chai', 'Patti', 'Chai Patti'],
    aliases: [
      'tea', 'black tea', 'tea leaves', 'tea bag', 'tapal', 'lipton',
      'chai', 'patti', 'chai patti', 'danedar',
      'چائے', 'پتی', 'چائے کی پتی',
    ],
    common_misspellings: ['chaee', 'patty'],
    category_id: 'grocery',
    subcategory_id: 'bev_tea_coffee',
    searchable_terms: ['tea', 'chai', 'patti', 'chai patti', 'چائے کی پتی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '☕',
    default_unit: 'packet',
    canonicalName: 'Tea (Chai Patti)',
    nameUrdu: 'چائے کی پتی',
    nameRomanUrdu: 'Chai Patti',
    categoryId: 'grocery',
    defaultUnit: 'packet',
  },
  {
    id: 'groc_coffee',
    canonical_name: 'Coffee',
    english_name: 'Coffee',
    urdu_name: 'کافی',
    roman_urdu_names: ['Coffee', 'Cofee'],
    aliases: [
      'coffee', 'instant coffee', 'nescafe',
      'cofee', 'kafi', 'coffey',
      'کافی',
    ],
    common_misspellings: ['cofee', 'kafi'],
    category_id: 'grocery',
    subcategory_id: 'bev_tea_coffee',
    searchable_terms: ['coffee', 'nescafe', 'کافی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '☕',
    default_unit: 'jar',
    canonicalName: 'Coffee',
    nameUrdu: 'کافی',
    nameRomanUrdu: 'Coffee',
    categoryId: 'grocery',
    defaultUnit: 'jar',
  },

  // ==========================================
  // 4. SPICES (مصالحہ جات)
  // ==========================================
  {
    id: 'spice_red_chili',
    canonical_name: 'Red Chili Powder',
    english_name: 'Red Chili Powder',
    urdu_name: 'سرخ مرچ پاؤڈر',
    roman_urdu_names: ['Lal Mirch', 'Surkh Mirch', 'Kuti Lal Mirch'],
    aliases: [
      'red chili', 'red chilli powder', 'chili flakes',
      'lal mirch', 'surkh mirch', 'laal mirch', 'kuti lal mirch', 'pisi lal mirch',
      'سرخ مرچ', 'لال مرچ', 'کٹی ہوئی لال مرچ',
    ],
    common_misspellings: ['laal mirch', 'chilli powder'],
    category_id: 'spices',
    subcategory_id: 'spice_ground',
    searchable_terms: ['red chili', 'lal mirch', 'surkh mirch', 'سرخ مرچ', 'لال مرچ'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🌶️',
    default_unit: 'pao',
    canonicalName: 'Red Chili Powder',
    nameUrdu: 'سرخ مرچ پاؤڈر',
    nameRomanUrdu: 'Lal Mirch',
    categoryId: 'spices',
    defaultUnit: 'pao',
  },
  {
    id: 'spice_turmeric',
    canonical_name: 'Turmeric Powder',
    english_name: 'Turmeric Powder',
    urdu_name: 'ہلدی',
    roman_urdu_names: ['Haldi', 'Huldi'],
    aliases: [
      'turmeric', 'turmeric powder',
      'haldi', 'huldi', 'pisi haldi',
      'ہلدی', 'پسی ہلدی',
    ],
    common_misspellings: ['tumeric', 'huldi'],
    category_id: 'spices',
    subcategory_id: 'spice_ground',
    searchable_terms: ['turmeric', 'haldi', 'ہلدی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🟡',
    default_unit: 'pao',
    canonicalName: 'Turmeric Powder',
    nameUrdu: 'ہلدی',
    nameRomanUrdu: 'Haldi',
    categoryId: 'spices',
    defaultUnit: 'pao',
  },
  {
    id: 'spice_cumin',
    canonical_name: 'Cumin (Zeera)',
    english_name: 'Cumin (Zeera)',
    urdu_name: 'سفید زیرہ',
    roman_urdu_names: ['Zeera', 'Zira', 'Safaid Zeera'],
    aliases: [
      'cumin', 'cumin seeds', 'jeera',
      'zeera', 'zira', 'safaid zeera', 'safed zeera', 'zeera powder',
      'زیرہ', 'سفید زیرہ',
    ],
    common_misspellings: ['jeera', 'zera', 'zeera'],
    category_id: 'spices',
    subcategory_id: 'spice_whole',
    searchable_terms: ['cumin', 'zeera', 'zira', 'jeera', 'زیرہ'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🌱',
    default_unit: 'pao',
    canonicalName: 'Cumin (Zeera)',
    nameUrdu: 'سفید زیرہ',
    nameRomanUrdu: 'Zeera',
    categoryId: 'spices',
    defaultUnit: 'pao',
  },
  {
    id: 'spice_coriander_powder',
    canonical_name: 'Coriander Powder',
    english_name: 'Coriander Powder',
    urdu_name: 'پسا دھنیا',
    roman_urdu_names: ['Pisa Dhaniya', 'Dhaniya Powder'],
    aliases: [
      'coriander powder', 'ground coriander',
      'pisa dhaniya', 'dhaniya powder', 'dhania powder',
      'پسا دھنیا', 'دھنیا پاؤڈر',
    ],
    common_misspellings: ['dhanya powder', 'dhaniapowder'],
    category_id: 'spices',
    subcategory_id: 'spice_ground',
    searchable_terms: ['coriander powder', 'dhaniya powder', 'pisa dhaniya', 'پسا دھنیا'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🌿',
    default_unit: 'pao',
    canonicalName: 'Coriander Powder',
    nameUrdu: 'پسا دھنیا',
    nameRomanUrdu: 'Pisa Dhaniya',
    categoryId: 'spices',
    defaultUnit: 'pao',
  },
  {
    id: 'spice_black_pepper',
    canonical_name: 'Black Pepper',
    english_name: 'Black Pepper',
    urdu_name: 'کالی مرچ',
    roman_urdu_names: ['Kali Mirch', 'Kaali Mirch'],
    aliases: [
      'black pepper', 'black peppercorns', 'pepper powder',
      'kali mirch', 'kaali mirch', 'sabut kali mirch', 'pisi kali mirch',
      'کالی مرچ', 'پسی کالی مرچ',
    ],
    common_misspellings: ['kaali mirch', 'blackpepper'],
    category_id: 'spices',
    subcategory_id: 'spice_whole',
    searchable_terms: ['black pepper', 'kali mirch', 'کالی مرچ'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '⚫',
    default_unit: 'pao',
    canonicalName: 'Black Pepper',
    nameUrdu: 'کالی مرچ',
    nameRomanUrdu: 'Kali Mirch',
    categoryId: 'spices',
    defaultUnit: 'pao',
  },
  {
    id: 'spice_cardamom',
    canonical_name: 'Green Cardamom (Choti Elaichi)',
    english_name: 'Green Cardamom',
    urdu_name: 'سبز الائچی',
    roman_urdu_names: ['Elaichi', 'Choti Elaichi', 'Sabz Elaichi'],
    aliases: [
      'cardamom', 'green cardamom', 'cardamoms',
      'elaichi', 'choti elaichi', 'sabz elaichi', 'ilaichi', 'elachi',
      'الائچی', 'سبز الائچی', 'چھوٹی الائچی',
    ],
    common_misspellings: ['ilaichi', 'elachi', 'choti ilaichi'],
    category_id: 'spices',
    subcategory_id: 'spice_whole',
    searchable_terms: ['cardamom', 'elaichi', 'choti elaichi', 'الائچی', 'سبز الائچی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🟢',
    default_unit: 'pao',
    canonicalName: 'Green Cardamom',
    nameUrdu: 'سبز الائچی',
    nameRomanUrdu: 'Elaichi',
    categoryId: 'spices',
    defaultUnit: 'pao',
  },
  {
    id: 'spice_cinnamon',
    canonical_name: 'Cinnamon (Dar Cheeni)',
    english_name: 'Cinnamon',
    urdu_name: 'دار چینی',
    roman_urdu_names: ['Dar Cheeni', 'Dar Chini', 'Dalchini'],
    aliases: [
      'cinnamon', 'cinnamon sticks', 'cinnamon powder',
      'dar cheeni', 'dar chini', 'darchini', 'dalchini', 'daalchini',
      'دار چینی', 'دارچینی',
    ],
    common_misspellings: ['cinamon', 'darchini'],
    category_id: 'spices',
    subcategory_id: 'spice_whole',
    searchable_terms: ['cinnamon', 'dar cheeni', 'dalchini', 'دار چینی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🪵',
    default_unit: 'pao',
    canonicalName: 'Cinnamon',
    nameUrdu: 'دار چینی',
    nameRomanUrdu: 'Dar Cheeni',
    categoryId: 'spices',
    defaultUnit: 'pao',
  },
  {
    id: 'spice_cloves',
    canonical_name: 'Cloves (Laung)',
    english_name: 'Cloves',
    urdu_name: 'لونگ',
    roman_urdu_names: ['Laung', 'Long'],
    aliases: [
      'cloves', 'clove',
      'laung', 'long', 'lavang',
      'لونگ',
    ],
    common_misspellings: ['laung', 'longg'],
    category_id: 'spices',
    subcategory_id: 'spice_whole',
    searchable_terms: ['cloves', 'laung', 'لونگ'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🌰',
    default_unit: 'pao',
    canonicalName: 'Cloves',
    nameUrdu: 'لونگ',
    nameRomanUrdu: 'Laung',
    categoryId: 'spices',
    defaultUnit: 'pao',
  },
  {
    id: 'spice_fennel',
    canonical_name: 'Fennel Seeds (Saunf)',
    english_name: 'Fennel Seeds',
    urdu_name: 'سونف',
    roman_urdu_names: ['Saunf', 'Sonf'],
    aliases: [
      'fennel', 'fennel seeds',
      'saunf', 'sonf', 'saanf',
      'سونف',
    ],
    common_misspellings: ['sonf', 'saanf'],
    category_id: 'spices',
    subcategory_id: 'spice_whole',
    searchable_terms: ['fennel', 'saunf', 'sonf', 'سونف'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🌾',
    default_unit: 'pao',
    canonicalName: 'Fennel Seeds',
    nameUrdu: 'سونف',
    nameRomanUrdu: 'Saunf',
    categoryId: 'spices',
    defaultUnit: 'pao',
  },
  {
    id: 'spice_fenugreek',
    canonical_name: 'Fenugreek Seeds (Methi Dana)',
    english_name: 'Fenugreek Seeds',
    urdu_name: 'میتھی دانہ',
    roman_urdu_names: ['Methi Dana', 'Maithi'],
    aliases: [
      'fenugreek', 'fenugreek seeds', 'methi',
      'methi dana', 'maithi dana', 'kasuri methi',
      'میتھی دانہ', 'قصوری میتھی',
    ],
    common_misspellings: ['methidana', 'kasuri methi'],
    category_id: 'spices',
    subcategory_id: 'spice_whole',
    searchable_terms: ['fenugreek', 'methi dana', 'میتھی دانہ', 'قصوری میتھی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🌿',
    default_unit: 'pao',
    canonicalName: 'Fenugreek Seeds',
    nameUrdu: 'میتھی دانہ',
    nameRomanUrdu: 'Methi Dana',
    categoryId: 'spices',
    defaultUnit: 'pao',
  },

  // ==========================================
  // 5. HERBAL & TRADITIONAL (جڑی بوٹیاں اور پنسار)
  // ==========================================
  {
    id: 'herbal_alum',
    canonical_name: 'Alum (Phitkari)',
    english_name: 'Alum',
    urdu_name: 'فٹکری',
    roman_urdu_names: ['Phitkari', 'Fitkari', 'Phatkari'],
    aliases: [
      'alum', 'potash alum',
      'phitkari', 'fitkari', 'phatkari', 'fatkari', 'phitkiri',
      'فٹکری', 'پھٹکری',
    ],
    common_misspellings: ['fitkiri', 'phitkri', 'phatkari', 'fatkari'],
    category_id: 'health',
    subcategory_id: 'health_firstaid',
    searchable_terms: ['alum', 'phitkari', 'fitkari', 'phatkari', 'فٹکری', 'پھٹکری'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🩹',
    default_unit: 'pcs',
    canonicalName: 'Alum (Phitkari)',
    nameUrdu: 'پھٹکری',
    nameRomanUrdu: 'Phitkari',
    categoryId: 'health',
    defaultUnit: 'pcs',
  },
  {
    id: 'herbal_isabgol',
    canonical_name: 'Isabgol (Psyllium Husk)',
    english_name: 'Psyllium Husk (Isabgol)',
    urdu_name: 'اسپغول چھلکا',
    roman_urdu_names: ['Isabgol', 'Ispaghol', 'Ispaghol Chilka'],
    aliases: [
      'isabgol', 'ispaghol', 'psyllium husk', 'isabgol husk',
      'isabghol', 'ispaghul', 'chilka isabgol',
      'اسپغول', 'اسبغول', 'چھلکا اسپغول',
    ],
    common_misspellings: ['ispaghol', 'isabghol', 'ispaghul'],
    category_id: 'herbal',
    subcategory_id: 'herbal_pansar',
    searchable_terms: ['isabgol', 'ispaghol', 'psyllium husk', 'اسپغول'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🌾',
    default_unit: 'packet',
    canonicalName: 'Isabgol',
    nameUrdu: 'اسپغول چھلکا',
    nameRomanUrdu: 'Isabgol',
    categoryId: 'herbal',
    defaultUnit: 'packet',
  },
  {
    id: 'herbal_senna',
    canonical_name: 'Senna Leaves (Sana Makki)',
    english_name: 'Senna Leaves',
    urdu_name: 'ثنا مکی',
    roman_urdu_names: ['Sana Makki', 'Sana al Makki'],
    aliases: [
      'senna', 'senna leaves', 'sana leaves',
      'sana makki', 'sana maki', 'sana al makki',
      'ثنا مکی', 'سنا مکی',
    ],
    common_misspellings: ['sanamakki', 'sana maki'],
    category_id: 'herbal',
    subcategory_id: 'herbal_pansar',
    searchable_terms: ['senna', 'sana makki', 'ثنا مکی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍃',
    default_unit: 'pao',
    canonicalName: 'Senna Leaves',
    nameUrdu: 'ثنا مکی',
    nameRomanUrdu: 'Sana Makki',
    categoryId: 'herbal',
    defaultUnit: 'pao',
  },
  {
    id: 'herbal_ajwain',
    canonical_name: 'Carom Seeds (Ajwain)',
    english_name: 'Carom Seeds (Ajwain)',
    urdu_name: 'اجوائن',
    roman_urdu_names: ['Ajwain', 'Ajwaen', 'Ajwan'],
    aliases: [
      'ajwain', 'carom seeds', 'ajwaen', 'ajwan', 'ajwayan',
      'اجوائن', 'اجواین',
    ],
    common_misspellings: ['ajwaen', 'ajwayan'],
    category_id: 'herbal',
    subcategory_id: 'herbal_pansar',
    searchable_terms: ['ajwain', 'carom seeds', 'ajwaen', 'اجوائن'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🌱',
    default_unit: 'pao',
    canonicalName: 'Carom Seeds',
    nameUrdu: 'اجوائن',
    nameRomanUrdu: 'Ajwain',
    categoryId: 'herbal',
    defaultUnit: 'pao',
  },
  {
    id: 'herbal_kalonji',
    canonical_name: 'Nigella Seeds (Kalonji)',
    english_name: 'Nigella Seeds (Kalonji)',
    urdu_name: 'کلونجی',
    roman_urdu_names: ['Kalonji', 'Kalwanji', 'Black Seeds'],
    aliases: [
      'kalonji', 'nigella seeds', 'black seed', 'kalwanji', 'kalonjee',
      'کلونجی',
    ],
    common_misspellings: ['kalonjee', 'kalwanji'],
    category_id: 'herbal',
    subcategory_id: 'herbal_pansar',
    searchable_terms: ['kalonji', 'nigella seeds', 'کلونجی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '⚫',
    default_unit: 'pao',
    canonicalName: 'Nigella Seeds',
    nameUrdu: 'کلونجی',
    nameRomanUrdu: 'Kalonji',
    categoryId: 'herbal',
    defaultUnit: 'pao',
  },
  {
    id: 'herbal_mulethi',
    canonical_name: 'Licorice Root (Mulethi)',
    english_name: 'Licorice Root',
    urdu_name: 'ملٹھی',
    roman_urdu_names: ['Mulethi', 'Mulathi'],
    aliases: [
      'mulethi', 'licorice', 'liquorice', 'mulathi', 'malathi',
      'ملٹھی',
    ],
    common_misspellings: ['mulathi', 'licorice'],
    category_id: 'herbal',
    subcategory_id: 'herbal_pansar',
    searchable_terms: ['mulethi', 'licorice', 'ملٹھی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🪵',
    default_unit: 'pao',
    canonicalName: 'Licorice Root',
    nameUrdu: 'ملٹھی',
    nameRomanUrdu: 'Mulethi',
    categoryId: 'herbal',
    defaultUnit: 'pao',
  },

  // ==========================================
  // 6. DAIRY (دودھ اور ڈیری)
  // ==========================================
  {
    id: 'dairy_milk',
    canonical_name: 'Fresh Milk',
    english_name: 'Fresh Milk',
    urdu_name: 'دودھ',
    roman_urdu_names: ['Doodh', 'Dudh', 'Tetra Pak Milk', 'Olpers', 'Milkpak'],
    aliases: [
      'milk', 'fresh milk', 'tetra pak milk', 'cow milk', 'buffalo milk',
      'doodh', 'dudh', 'olpers', 'milkpak', 'khula doodh',
      'دودھ', 'کھلا دودھ', 'اولپرز', 'ملک پیک',
    ],
    common_misspellings: ['dood', 'dud'],
    category_id: 'dairy',
    subcategory_id: 'dairy_milk',
    searchable_terms: ['milk', 'doodh', 'dudh', 'olpers', 'milkpak', 'دودھ'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🥛',
    default_unit: 'liter',
    canonicalName: 'Fresh Milk',
    nameUrdu: 'دودھ',
    nameRomanUrdu: 'Doodh',
    categoryId: 'dairy',
    defaultUnit: 'liter',
  },
  {
    id: 'dairy_yogurt',
    canonical_name: 'Yogurt (Dahi)',
    english_name: 'Yogurt',
    urdu_name: 'دہی',
    roman_urdu_names: ['Dahi', 'Dahii', 'Curd'],
    aliases: [
      'yogurt', 'yoghurt', 'curd',
      'dahi', 'dahii', 'meetha dahi', 'khatta dahi',
      'دہی',
    ],
    common_misspellings: ['yoghurt', 'dhee'],
    category_id: 'dairy',
    subcategory_id: 'dairy_yogurt_butter',
    searchable_terms: ['yogurt', 'curd', 'dahi', 'دہی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🥣',
    default_unit: 'kg',
    canonicalName: 'Yogurt',
    nameUrdu: 'دہی',
    nameRomanUrdu: 'Dahi',
    categoryId: 'dairy',
    defaultUnit: 'kg',
  },
  {
    id: 'dairy_butter',
    canonical_name: 'Butter',
    english_name: 'Butter',
    urdu_name: 'مکھن',
    roman_urdu_names: ['Makhan', 'Makkhan', 'Butter'],
    aliases: [
      'butter', 'salted butter', 'unsalted butter', 'nurpur butter', 'lurpuk',
      'makhan', 'makkhan', 'desi makhan',
      'مکھن', 'دیسی مکھن',
    ],
    common_misspellings: ['buttr', 'makkhan'],
    category_id: 'dairy',
    subcategory_id: 'dairy_yogurt_butter',
    searchable_terms: ['butter', 'makhan', 'مکھن'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧈',
    default_unit: 'packet',
    canonicalName: 'Butter',
    nameUrdu: 'مکھن',
    nameRomanUrdu: 'Makhan',
    categoryId: 'dairy',
    defaultUnit: 'packet',
  },
  {
    id: 'dairy_cheese',
    canonical_name: 'Cheese',
    english_name: 'Cheese',
    urdu_name: 'پنیر',
    roman_urdu_names: ['Cheese', 'Paneer'],
    aliases: [
      'cheese', 'cheddar cheese', 'mozzarella cheese', 'cheese slices',
      'paneer', 'cheez',
      'پنیر', 'چیز',
    ],
    common_misspellings: ['cheez', 'paneer'],
    category_id: 'dairy',
    subcategory_id: 'dairy_yogurt_butter',
    searchable_terms: ['cheese', 'paneer', 'پنیر', 'چیز'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧀',
    default_unit: 'packet',
    canonicalName: 'Cheese',
    nameUrdu: 'پنیر',
    nameRomanUrdu: 'Cheese',
    categoryId: 'dairy',
    defaultUnit: 'packet',
  },
  {
    id: 'dairy_cream',
    canonical_name: 'Fresh Cream',
    english_name: 'Fresh Cream',
    urdu_name: 'بالائی / کریم',
    roman_urdu_names: ['Cream', 'Malai', 'Balai'],
    aliases: [
      'cream', 'fresh cream', 'whipping cream', 'milkpak cream',
      'malai', 'balai', 'creem',
      'ملائی', 'کریم', 'بالائی',
    ],
    common_misspellings: ['creem', 'malai'],
    category_id: 'dairy',
    subcategory_id: 'dairy_milk',
    searchable_terms: ['cream', 'fresh cream', 'malai', 'ملائی', 'کریم'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🥛',
    default_unit: 'packet',
    canonicalName: 'Fresh Cream',
    nameUrdu: 'کریم',
    nameRomanUrdu: 'Cream',
    categoryId: 'dairy',
    defaultUnit: 'packet',
  },

  // ==========================================
  // 7. BAKERY (بیکری اور روٹی)
  // ==========================================
  {
    id: 'bakery_bread',
    canonical_name: 'Bread (Double Roti)',
    english_name: 'Bread',
    urdu_name: 'ڈبل روٹی',
    roman_urdu_names: ['Bread', 'Double Roti', 'Dawn Bread'],
    aliases: [
      'bread', 'sliced bread', 'white bread', 'brown bread', 'dawn bread',
      'double roti', 'dabal roti', 'duble roti',
      'ڈبل روٹی', 'بریڈ',
    ],
    common_misspellings: ['dabal roti', 'bred'],
    category_id: 'bakery',
    subcategory_id: 'bakery_breads',
    searchable_terms: ['bread', 'double roti', 'ڈبل روٹی', 'بریڈ'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍞',
    default_unit: 'packet',
    canonicalName: 'Bread',
    nameUrdu: 'ڈبل روٹی',
    nameRomanUrdu: 'Bread',
    categoryId: 'bakery',
    defaultUnit: 'packet',
  },
  {
    id: 'bakery_buns',
    canonical_name: 'Burger Buns',
    english_name: 'Burger Buns',
    urdu_name: 'برگر بن',
    roman_urdu_names: ['Buns', 'Burger Buns', 'Bun'],
    aliases: [
      'buns', 'bun', 'burger buns', 'dinner rolls',
      'burger bun', 'bunn',
      'بن', 'برگر بن',
    ],
    common_misspellings: ['bunn', 'burgur bun'],
    category_id: 'bakery',
    subcategory_id: 'bakery_breads',
    searchable_terms: ['buns', 'burger buns', 'برگر بن'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍔',
    default_unit: 'packet',
    canonicalName: 'Burger Buns',
    nameUrdu: 'برگر بن',
    nameRomanUrdu: 'Burger Buns',
    categoryId: 'bakery',
    defaultUnit: 'packet',
  },
  {
    id: 'bakery_cake',
    canonical_name: 'Tea Cake',
    english_name: 'Tea Cake',
    urdu_name: 'کیک',
    roman_urdu_names: ['Cake', 'Tea Cake', 'Fruit Cake'],
    aliases: [
      'cake', 'tea cake', 'plain cake', 'fruit cake',
      'kake', 'cupcake',
      'کیک', 'ٹی کیک',
    ],
    common_misspellings: ['kake', 'teacake'],
    category_id: 'bakery',
    subcategory_id: 'bakery_rusks',
    searchable_terms: ['cake', 'tea cake', 'کیک'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍰',
    default_unit: 'pcs',
    canonicalName: 'Tea Cake',
    nameUrdu: 'کیک',
    nameRomanUrdu: 'Cake',
    categoryId: 'bakery',
    defaultUnit: 'pcs',
  },
  {
    id: 'bakery_biscuits',
    canonical_name: 'Biscuits',
    english_name: 'Biscuits',
    urdu_name: 'بسکٹ',
    roman_urdu_names: ['Biscuits', 'Biscut', 'Cookies'],
    aliases: [
      'biscuits', 'biscuit', 'cookies', 'sooper', 'marie', 'zeera plus',
      'biscut', 'biskit',
      'بسکٹ', 'کوکیز',
    ],
    common_misspellings: ['biscut', 'biskit'],
    category_id: 'bakery',
    subcategory_id: 'bakery_rusks',
    searchable_terms: ['biscuits', 'cookies', 'biscuit', 'بسکٹ'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍪',
    default_unit: 'packet',
    canonicalName: 'Biscuits',
    nameUrdu: 'بسکٹ',
    nameRomanUrdu: 'Biscuits',
    categoryId: 'bakery',
    defaultUnit: 'packet',
  },
  {
    id: 'bakery_rusks',
    canonical_name: 'Rusks (Cake Rusk)',
    english_name: 'Rusks',
    urdu_name: 'رس / کیک رس',
    roman_urdu_names: ['Rusk', 'Cake Rusk'],
    aliases: [
      'rusk', 'rusks', 'cake rusk', 'sooji rusk',
      'ras', 'cake ras',
      'رس', 'کیک رس',
    ],
    common_misspellings: ['ruske', 'ras'],
    category_id: 'bakery',
    subcategory_id: 'bakery_rusks',
    searchable_terms: ['rusk', 'cake rusk', 'رس', 'کیک رس'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🥖',
    default_unit: 'packet',
    canonicalName: 'Rusks',
    nameUrdu: 'رس',
    nameRomanUrdu: 'Rusk',
    categoryId: 'bakery',
    defaultUnit: 'packet',
  },

  // ==========================================
  // 8. MEAT (گوشت اور چکن)
  // ==========================================
  {
    id: 'meat_chicken',
    canonical_name: 'Chicken',
    english_name: 'Chicken',
    urdu_name: 'مرغی کا گوشت',
    roman_urdu_names: ['Chicken', 'Murghi', 'Murgh'],
    aliases: [
      'chicken', 'broiler chicken', 'desi chicken', 'boneless chicken', 'chicken mince',
      'murghi', 'murghi ka gosht', 'chiken',
      'مرغی', 'چکن', 'مرغی کا گوشت',
    ],
    common_misspellings: ['chiken', 'murgi'],
    category_id: 'meat',
    subcategory_id: 'meat_poultry',
    searchable_terms: ['chicken', 'murghi', 'چکن', 'مرغی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍗',
    default_unit: 'kg',
    canonicalName: 'Chicken',
    nameUrdu: 'مرغی کا گوشت',
    nameRomanUrdu: 'Chicken',
    categoryId: 'meat',
    defaultUnit: 'kg',
  },
  {
    id: 'meat_beef',
    canonical_name: 'Beef (Gaye Ka Gosht)',
    english_name: 'Beef',
    urdu_name: 'بڑا گوشت / گائے',
    roman_urdu_names: ['Beef', 'Bara Gosht', 'Gaye ka Gosht'],
    aliases: [
      'beef', 'cow meat', 'veal', 'beef mince', 'beef boneless',
      'bara gosht', 'gaye ka gosht', 'bada gosht', 'qeema beef',
      'بیف', 'بڑا گوشت', 'گائے کا گوشت',
    ],
    common_misspellings: ['bada gosht', 'gai ka gosht'],
    category_id: 'meat',
    subcategory_id: 'meat_beef',
    searchable_terms: ['beef', 'bara gosht', 'gaye ka gosht', 'بیف', 'بڑا گوشت'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🥩',
    default_unit: 'kg',
    canonicalName: 'Beef',
    nameUrdu: 'بڑا گوشت',
    nameRomanUrdu: 'Beef',
    categoryId: 'meat',
    defaultUnit: 'kg',
  },
  {
    id: 'meat_mutton',
    canonical_name: 'Mutton (Bakra)',
    english_name: 'Mutton',
    urdu_name: 'چھوٹا گوشت / بکرا',
    roman_urdu_names: ['Mutton', 'Chota Gosht', 'Bakra'],
    aliases: [
      'mutton', 'goat meat', 'lamb', 'mutton chops', 'mutton mince',
      'chota gosht', 'bakra', 'bakray ka gosht', 'dumba',
      'مٹن', 'چھوٹا گوشت', 'بکرے کا گوشت',
    ],
    common_misspellings: ['chota gosht', 'bakre ka gosht'],
    category_id: 'meat',
    subcategory_id: 'meat_mutton',
    searchable_terms: ['mutton', 'chota gosht', 'bakra', 'مٹن', 'چھوٹا گوشت'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍖',
    default_unit: 'kg',
    canonicalName: 'Mutton',
    nameUrdu: 'چھوٹا گوشت',
    nameRomanUrdu: 'Mutton',
    categoryId: 'meat',
    defaultUnit: 'kg',
  },

  // ==========================================
  // 9. SEAFOOD (مچھلی اور سی فوڈ)
  // ==========================================
  {
    id: 'seafood_fish',
    canonical_name: 'Fish (Machli)',
    english_name: 'Fish',
    urdu_name: 'مچھلی',
    roman_urdu_names: ['Machli', 'Machhli', 'Fish'],
    aliases: [
      'fish', 'rohu', 'surmai', 'pomfret', 'finger fish', 'fish fillets',
      'machli', 'machhli', 'rahu', 'mushka',
      'مچھلی', 'روہو', 'سرمئی',
    ],
    common_misspellings: ['machhli', 'machli'],
    category_id: 'seafood',
    subcategory_id: 'seafood_fish',
    searchable_terms: ['fish', 'machli', 'مچھلی', 'روہو'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🐟',
    default_unit: 'kg',
    canonicalName: 'Fish',
    nameUrdu: 'مچھلی',
    nameRomanUrdu: 'Machli',
    categoryId: 'seafood',
    defaultUnit: 'kg',
  },
  {
    id: 'seafood_prawns',
    canonical_name: 'Prawns / Shrimps',
    english_name: 'Prawns / Shrimps',
    urdu_name: 'جھینگا',
    roman_urdu_names: ['Jheenga', 'Prawns', 'Shrimp'],
    aliases: [
      'prawns', 'shrimps', 'shrimp', 'prawn',
      'jheenga', 'jhinga', 'jeenga',
      'جھینگا', 'پرانز',
    ],
    common_misspellings: ['jhinga', 'jeenga'],
    category_id: 'seafood',
    subcategory_id: 'seafood_shellfish',
    searchable_terms: ['prawns', 'shrimps', 'jheenga', 'جھینگا'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🦐',
    default_unit: 'kg',
    canonicalName: 'Prawns',
    nameUrdu: 'جھینگا',
    nameRomanUrdu: 'Jheenga',
    categoryId: 'seafood',
    defaultUnit: 'kg',
  },

  // ==========================================
  // 10. EGGS (انڈے)
  // ==========================================
  {
    id: 'eggs_farm',
    canonical_name: 'Eggs (Anday)',
    english_name: 'Eggs',
    urdu_name: 'انڈے',
    roman_urdu_names: ['Anday', 'Ande', 'Eggs'],
    aliases: [
      'eggs', 'egg', 'white eggs', 'farm eggs', 'desi eggs',
      'anday', 'ande', 'anda', 'desi anday', 'farmi anday',
      'انڈے', 'انڈا', 'دیسی انڈے',
    ],
    common_misspellings: ['ande', 'andayy'],
    category_id: 'eggs',
    subcategory_id: 'eggs_farm',
    searchable_terms: ['eggs', 'egg', 'anday', 'ande', 'انڈے'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🥚',
    default_unit: 'dozen',
    canonicalName: 'Eggs',
    nameUrdu: 'انڈے',
    nameRomanUrdu: 'Anday',
    categoryId: 'eggs',
    defaultUnit: 'dozen',
  },

  // ==========================================
  // 11. BEVERAGES (مشروبات اور شربت)
  // ==========================================
  {
    id: 'bev_rooh_afza',
    canonical_name: 'Rooh Afza / Red Syrup',
    english_name: 'Rooh Afza',
    urdu_name: 'روح افزا',
    roman_urdu_names: ['Rooh Afza', 'Jam e Shirin', 'Lal Sharbat'],
    aliases: [
      'rooh afza', 'roohafza', 'jam e shirin', 'jam-e-shirin', 'red syrup',
      'lal sharbat', 'sharbat',
      'روح افزا', 'جام شیریں', 'لال شربت',
    ],
    common_misspellings: ['roohafza', 'jameshiri'],
    category_id: 'beverages',
    subcategory_id: 'bev_syrups',
    searchable_terms: ['rooh afza', 'jam e shirin', 'sharbat', 'روح افزا'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🍷',
    default_unit: 'bottle',
    canonicalName: 'Rooh Afza',
    nameUrdu: 'روح افزا',
    nameRomanUrdu: 'Rooh Afza',
    categoryId: 'beverages',
    defaultUnit: 'bottle',
  },
  {
    id: 'bev_mineral_water',
    canonical_name: 'Mineral Water',
    english_name: 'Mineral Water',
    urdu_name: 'منرل واٹر / پانی',
    roman_urdu_names: ['Mineral Water', 'Paani', 'Nestle Water'],
    aliases: [
      'water', 'mineral water', 'nestle water', 'aquafina', 'drinking water',
      'paani', 'pani', 'pani ki bottle',
      'منرل واٹر', 'پانی کی بوتل', 'پانی',
    ],
    common_misspellings: ['pani', 'mineralwater'],
    category_id: 'beverages',
    subcategory_id: 'bev_water_soda',
    searchable_terms: ['mineral water', 'water', 'paani', 'پانی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '💧',
    default_unit: 'bottle',
    canonicalName: 'Mineral Water',
    nameUrdu: 'منرل واٹر',
    nameRomanUrdu: 'Mineral Water',
    categoryId: 'beverages',
    defaultUnit: 'bottle',
  },

  // ==========================================
  // 12. PERSONAL CARE (ذاتی دیکھ بھال)
  // ==========================================
  {
    id: 'pc_soap',
    canonical_name: 'Bath Soap',
    english_name: 'Bath Soap',
    urdu_name: 'نہانے کا صابن',
    roman_urdu_names: ['Sabun', 'Soap', 'Lux', 'Lifebuoy'],
    aliases: [
      'soap', 'bath soap', 'beauty soap', 'lux', 'lifebuoy', 'dettol soap', 'safeguard',
      'sabun', 'nahane ka sabun', 'saabun',
      'صابن', 'نہانے کا صابن',
    ],
    common_misspellings: ['saabun', 'sabon'],
    category_id: 'personal_care',
    subcategory_id: 'pc_bath',
    searchable_terms: ['soap', 'bath soap', 'sabun', 'صابن'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧼',
    default_unit: 'pcs',
    canonicalName: 'Bath Soap',
    nameUrdu: 'نہانے کا صابن',
    nameRomanUrdu: 'Sabun',
    categoryId: 'personal_care',
    defaultUnit: 'pcs',
  },
  {
    id: 'pc_shampoo',
    canonical_name: 'Shampoo',
    english_name: 'Shampoo',
    urdu_name: 'شیمپو',
    roman_urdu_names: ['Shampoo', 'Shampu', 'Sunsilk', 'Head & Shoulders'],
    aliases: [
      'shampoo', 'hair shampoo', 'sunsilk', 'pantene', 'head and shoulders',
      'shampu', 'shampooki bottle',
      'شیمپو',
    ],
    common_misspellings: ['shampu', 'shampo'],
    category_id: 'personal_care',
    subcategory_id: 'pc_hair',
    searchable_terms: ['shampoo', 'shampu', 'شیمپو'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧴',
    default_unit: 'bottle',
    canonicalName: 'Shampoo',
    nameUrdu: 'شیمپو',
    nameRomanUrdu: 'Shampoo',
    categoryId: 'personal_care',
    defaultUnit: 'bottle',
  },
  {
    id: 'pc_toothpaste',
    canonical_name: 'Toothpaste',
    english_name: 'Toothpaste',
    urdu_name: 'ٹوتھ پیسٹ',
    roman_urdu_names: ['Toothpaste', 'Colgate', 'Sensodyne', 'Tooth Paste'],
    aliases: [
      'toothpaste', 'tooth paste', 'colgate', 'sensodyne', 'close up',
      'paste', 'dant ki paste',
      'ٹوتھ پیسٹ', 'پیسٹ',
    ],
    common_misspellings: ['toothpast', 'tooth pest'],
    category_id: 'personal_care',
    subcategory_id: 'pc_dental',
    searchable_terms: ['toothpaste', 'colgate', 'ٹوتھ پیسٹ'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🪥',
    default_unit: 'pcs',
    canonicalName: 'Toothpaste',
    nameUrdu: 'ٹوتھ پیسٹ',
    nameRomanUrdu: 'Toothpaste',
    categoryId: 'personal_care',
    defaultUnit: 'pcs',
  },

  // ==========================================
  // 13. HOUSEHOLD (گھریلو اشیاء)
  // ==========================================
  {
    id: 'hh_tissue_roll',
    canonical_name: 'Tissue Roll / Paper Towel',
    english_name: 'Tissue Roll',
    urdu_name: 'ٹشو رول',
    roman_urdu_names: ['Tissue', 'Tissue Roll', 'Rose Petal'],
    aliases: [
      'tissue', 'tissue roll', 'paper towel', 'kitchen roll', 'rose petal', 'facial tissue',
      'tishu', 'tissue box',
      'ٹشو', 'ٹشو رول', 'ٹشو پیپر',
    ],
    common_misspellings: ['tishu', 'tissu'],
    category_id: 'household',
    subcategory_id: 'hh_paper',
    searchable_terms: ['tissue', 'tissue roll', 'paper towel', 'ٹشو'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧻',
    default_unit: 'pack',
    canonicalName: 'Tissue Roll',
    nameUrdu: 'ٹشو رول',
    nameRomanUrdu: 'Tissue',
    categoryId: 'household',
    defaultUnit: 'pack',
  },
  {
    id: 'hh_trash_bags',
    canonical_name: 'Trash Bags / Shopper',
    english_name: 'Trash Bags',
    urdu_name: 'کچرے کے شاپر',
    roman_urdu_names: ['Trash Bags', 'Kachra Bag', 'Shopper'],
    aliases: [
      'trash bags', 'garbage bags', 'dustbin bags',
      'kachra bag', 'kachray ke shopper', 'lifafay',
      'کچرے کے شاپر', 'ڈسٹ بن بیگ',
    ],
    common_misspellings: ['garbag bag', 'kachra bag'],
    category_id: 'household',
    subcategory_id: 'hh_bags_utility',
    searchable_terms: ['trash bags', 'garbage bags', 'kachra bag', 'کچرے کے شاپر'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🗑️',
    default_unit: 'pack',
    canonicalName: 'Trash Bags',
    nameUrdu: 'کچرے کے شاپر',
    nameRomanUrdu: 'Trash Bags',
    categoryId: 'household',
    defaultUnit: 'pack',
  },

  // ==========================================
  // 14. CLEANING (صفائی اور سرف)
  // ==========================================
  {
    id: 'clean_surf',
    canonical_name: 'Washing Powder (Surf)',
    english_name: 'Washing Powder',
    urdu_name: 'سرف / واشنگ پاؤڈر',
    roman_urdu_names: ['Surf', 'Washing Powder', 'Surf Excel', 'Ariel', 'Bonus'],
    aliases: [
      'surf', 'washing powder', 'detergent', 'surf excel', 'ariel', 'bonus', 'bright',
      'sarf', 'kapray dhonay ka powder',
      'سرف', 'واشنگ پاؤڈر', 'ڈیٹرجنٹ',
    ],
    common_misspellings: ['sarf', 'washin powder'],
    category_id: 'cleaning',
    subcategory_id: 'clean_laundry',
    searchable_terms: ['surf', 'washing powder', 'detergent', 'ariel', 'سرف'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧺',
    default_unit: 'kg',
    canonicalName: 'Washing Powder',
    nameUrdu: 'سرف',
    nameRomanUrdu: 'Surf',
    categoryId: 'cleaning',
    defaultUnit: 'kg',
  },
  {
    id: 'clean_dishwash',
    canonical_name: 'Dishwashing Soap / Bar',
    english_name: 'Dishwashing Soap',
    urdu_name: 'برتن دھونے کا صابن / وم',
    roman_urdu_names: ['Dishwash', 'Bartan ka Sabun', 'Vim Bar', 'Lemon Max'],
    aliases: [
      'dishwash', 'dishwashing soap', 'dishwashing bar', 'dishwashing liquid', 'vim', 'lemon max',
      'bartan dhonay ka sabun', 'bartan wala sabun', 'max bar',
      'برتن دھونے کا صابن', 'وم بار', 'ڈش واش',
    ],
    common_misspellings: ['dish wash', 'vimbar'],
    category_id: 'cleaning',
    subcategory_id: 'clean_dish',
    searchable_terms: ['dishwash', 'vim bar', 'lemon max', 'bartan sabun', 'برتن دھونے کا صابن'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧼',
    default_unit: 'pcs',
    canonicalName: 'Dishwashing Soap',
    nameUrdu: 'برتن دھونے کا صابن',
    nameRomanUrdu: 'Dishwash',
    categoryId: 'cleaning',
    defaultUnit: 'pcs',
  },
  {
    id: 'clean_harpic',
    canonical_name: 'Toilet Cleaner (Harpic)',
    english_name: 'Toilet Cleaner',
    urdu_name: 'ہارپک / ٹوائلٹ کلینر',
    roman_urdu_names: ['Harpic', 'Toilet Cleaner'],
    aliases: [
      'harpic', 'toilet cleaner', 'bathroom cleaner',
      'harpik', 'flush cleaner',
      'ہارپک', 'ٹوائلٹ کلینر',
    ],
    common_misspellings: ['harpik', 'harpek'],
    category_id: 'cleaning',
    subcategory_id: 'clean_floor',
    searchable_terms: ['harpic', 'toilet cleaner', 'ہارپک'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🚽',
    default_unit: 'bottle',
    canonicalName: 'Toilet Cleaner',
    nameUrdu: 'ہارپک',
    nameRomanUrdu: 'Harpic',
    categoryId: 'cleaning',
    defaultUnit: 'bottle',
  },
  {
    id: 'clean_phenyl',
    canonical_name: 'Phenyl (Floor Cleaner)',
    english_name: 'Phenyl',
    urdu_name: 'فنائل',
    roman_urdu_names: ['Phenyl', 'Finail', 'Floor Cleaner'],
    aliases: [
      'phenyl', 'finail', 'floor cleaner', 'dettol floor cleaner',
      'fynile', 'safai ka phenyl',
      'فنائل',
    ],
    common_misspellings: ['finail', 'phenyle'],
    category_id: 'cleaning',
    subcategory_id: 'clean_floor',
    searchable_terms: ['phenyl', 'floor cleaner', 'فنائل'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧴',
    default_unit: 'bottle',
    canonicalName: 'Phenyl',
    nameUrdu: 'فنائل',
    nameRomanUrdu: 'Phenyl',
    categoryId: 'cleaning',
    defaultUnit: 'bottle',
  },

  // ==========================================
  // 15. HEALTH & PHARMACY (صحت اور ادویات)
  // ==========================================
  {
    id: 'health_panadol',
    canonical_name: 'Paracetamol (Panadol)',
    english_name: 'Paracetamol (Panadol)',
    urdu_name: 'پیناڈول / پیراسیٹامول',
    roman_urdu_names: ['Panadol', 'Paracetamol', 'Disprin'],
    aliases: [
      'panadol', 'paracetamol', 'disprin', 'panadol cf', 'painkiller',
      'bukhar ki goli', 'dard ki goli', 'sardard ki goli',
      'پیناڈول', 'پیراسیٹامول', 'ڈسپرین', 'بخار کی گولی',
    ],
    common_misspellings: ['panadoll', 'panadol'],
    category_id: 'health',
    subcategory_id: 'health_firstaid',
    searchable_terms: ['panadol', 'paracetamol', 'disprin', 'پیناڈول'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '💊',
    default_unit: 'strip',
    canonicalName: 'Panadol',
    nameUrdu: 'پیناڈول',
    nameRomanUrdu: 'Panadol',
    categoryId: 'health',
    defaultUnit: 'strip',
  },
  {
    id: 'health_dettol',
    canonical_name: 'Dettol Antiseptic',
    english_name: 'Dettol Antiseptic',
    urdu_name: 'ڈیٹول مائع',
    roman_urdu_names: ['Dettol', 'Dettol Liquid'],
    aliases: [
      'dettol', 'antiseptic liquid', 'dettol liquid',
      'detol', 'zakham ka dettol',
      'ڈیٹول', 'جراثیم کش مائع',
    ],
    common_misspellings: ['detol', 'dettoll'],
    category_id: 'health',
    subcategory_id: 'health_firstaid',
    searchable_terms: ['dettol', 'antiseptic', 'ڈیٹول'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🩹',
    default_unit: 'bottle',
    canonicalName: 'Dettol',
    nameUrdu: 'ڈیٹول',
    nameRomanUrdu: 'Dettol',
    categoryId: 'health',
    defaultUnit: 'bottle',
  },
  {
    id: 'health_saniplast',
    canonical_name: 'Bandage (Saniplast)',
    english_name: 'Bandage (Saniplast)',
    urdu_name: 'سنی پلاس / پٹی',
    roman_urdu_names: ['Saniplast', 'Bandage', 'Plaster'],
    aliases: [
      'saniplast', 'bandage', 'band aid', 'adhesive plaster',
      'sunny plast', 'zakham ki patti',
      'سنی پلاس', 'پٹی', 'بینڈ ایڈ',
    ],
    common_misspellings: ['sani plast', 'sunnyplast'],
    category_id: 'health',
    subcategory_id: 'health_firstaid',
    searchable_terms: ['saniplast', 'bandage', 'سنی پلاس', 'پٹی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🩹',
    default_unit: 'pack',
    canonicalName: 'Saniplast',
    nameUrdu: 'سنی پلاس',
    nameRomanUrdu: 'Saniplast',
    categoryId: 'health',
    defaultUnit: 'pack',
  },

  // ==========================================
  // 16. BABY CARE (بچوں کی دیکھ بھال)
  // ==========================================
  {
    id: 'baby_diapers',
    canonical_name: 'Baby Diapers (Pampers)',
    english_name: 'Baby Diapers',
    urdu_name: 'ڈائپرز / پیمپرز',
    roman_urdu_names: ['Diapers', 'Pampers', 'Baby Diaper'],
    aliases: [
      'diapers', 'diaper', 'pampers', 'molfix', 'canbebe',
      'daipar', 'pampar', 'bachay ke pamper',
      'ڈائپرز', 'پیمپرز',
    ],
    common_misspellings: ['pampar', 'daipar'],
    category_id: 'baby_care',
    subcategory_id: 'baby_diapers',
    searchable_terms: ['diapers', 'pampers', 'ڈائپرز', 'پیمپرز'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '👶',
    default_unit: 'pack',
    canonicalName: 'Baby Diapers',
    nameUrdu: 'پیمپرز',
    nameRomanUrdu: 'Pampers',
    categoryId: 'baby_care',
    defaultUnit: 'pack',
  },
  {
    id: 'baby_cerelac',
    canonical_name: 'Cerelac Baby Cereal',
    english_name: 'Cerelac Baby Food',
    urdu_name: 'سیریلاک',
    roman_urdu_names: ['Cerelac', 'Baby Cereal', 'Nestle Cerelac'],
    aliases: [
      'cerelac', 'baby cereal', 'baby food', 'nestle cerelac',
      'serilac', 'cerilac',
      'سیریلاک', 'بے بی فوڈ',
    ],
    common_misspellings: ['serilac', 'cerilac'],
    category_id: 'baby_care',
    subcategory_id: 'baby_nutrition',
    searchable_terms: ['cerelac', 'baby food', 'سیریلاک'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🥣',
    default_unit: 'box',
    canonicalName: 'Cerelac',
    nameUrdu: 'سیریلاک',
    nameRomanUrdu: 'Cerelac',
    categoryId: 'baby_care',
    defaultUnit: 'box',
  },

  // ==========================================
  // 17. PET SUPPLIES (پالتو جانوروں کا سامان)
  // ==========================================
  {
    id: 'pet_cat_food',
    canonical_name: 'Cat Food',
    english_name: 'Cat Food',
    urdu_name: 'بلی کی خوراک',
    roman_urdu_names: ['Cat Food', 'Billi ki Khorak', 'Me-O', 'Whiskas'],
    aliases: [
      'cat food', 'kitten food', 'me-o', 'whiskas', 'royal canin',
      'billi ki khorak', 'billi ka khana',
      'بلی کی خوراک', 'کیٹ فوڈ',
    ],
    common_misspellings: ['catfood', 'billi khana'],
    category_id: 'pet_supplies',
    subcategory_id: 'pet_food',
    searchable_terms: ['cat food', 'billi ki khorak', 'بلی کی خوراک'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🐱',
    default_unit: 'packet',
    canonicalName: 'Cat Food',
    nameUrdu: 'بلی کی خوراک',
    nameRomanUrdu: 'Cat Food',
    categoryId: 'pet_supplies',
    defaultUnit: 'packet',
  },

  // ==========================================
  // 18. HOME & LIVING (گھر اور سجاوٹ)
  // ==========================================
  {
    id: 'home_towel',
    canonical_name: 'Bath Towel',
    english_name: 'Bath Towel',
    urdu_name: 'تولیہ',
    roman_urdu_names: ['Towel', 'Toliya', 'Towal'],
    aliases: [
      'towel', 'bath towel', 'hand towel',
      'toliya', 'towal',
      'تولیہ',
    ],
    common_misspellings: ['toliya', 'towal'],
    category_id: 'home',
    subcategory_id: 'home_linen',
    searchable_terms: ['towel', 'bath towel', 'toliya', 'تولیہ'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧖',
    default_unit: 'pcs',
    canonicalName: 'Bath Towel',
    nameUrdu: 'تولیہ',
    nameRomanUrdu: 'Towel',
    categoryId: 'home',
    defaultUnit: 'pcs',
  },

  // ==========================================
  // 19. HARDWARE (ہارڈویئر اور چونا)
  // ==========================================
  {
    id: 'hw_limestone',
    canonical_name: 'Limestone (Choona)',
    english_name: 'Limestone',
    urdu_name: 'چونا',
    roman_urdu_names: ['Choona', 'Chuna'],
    aliases: [
      'lime stone', 'limestone', 'choona', 'chuna', 'lime powder', 'slaked lime', 'quicklime', 'calcium carbonate',
      'چونا', 'سفیدی',
    ],
    common_misspellings: ['limeston', 'chuna'],
    category_id: 'hardware',
    subcategory_id: 'hw_materials',
    searchable_terms: ['lime stone', 'limestone', 'choona', 'chuna', 'چونا'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧱',
    default_unit: 'kg',
    canonicalName: 'Limestone',
    nameUrdu: 'چونا',
    nameRomanUrdu: 'Choona',
    categoryId: 'hardware',
    defaultUnit: 'kg',
  },
  {
    id: 'hw_super_glue',
    canonical_name: 'Super Glue (Elfy)',
    english_name: 'Super Glue (Elfy)',
    urdu_name: 'ایلفی / گلو',
    roman_urdu_names: ['Elfy', 'Alfy', 'Super Glue'],
    aliases: [
      'elfy', 'super glue', 'alfy', 'glue', 'instant glue', 'samad bond',
      'ایلفی', 'الفے', 'سمد بونڈ',
    ],
    common_misspellings: ['alfy', 'elphy'],
    category_id: 'hardware',
    subcategory_id: 'hw_materials',
    searchable_terms: ['elfy', 'super glue', 'ایلفی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧴',
    default_unit: 'pcs',
    canonicalName: 'Super Glue',
    nameUrdu: 'ایلفی',
    nameRomanUrdu: 'Elfy',
    categoryId: 'hardware',
    defaultUnit: 'pcs',
  },
  {
    id: 'hw_led_bulb',
    canonical_name: 'LED Bulb',
    english_name: 'LED Bulb',
    urdu_name: 'ایل ای ڈی بلب',
    roman_urdu_names: ['LED Bulb', 'Bulb', 'Light Bulb'],
    aliases: [
      'led bulb', 'bulb', 'light bulb', '12w bulb', 'energy saver',
      'balab', 'bijli ka bulb',
      'بلب', 'ایل ای ڈی بلب',
    ],
    common_misspellings: ['balab', 'bulab'],
    category_id: 'hardware',
    subcategory_id: 'hw_electrical',
    searchable_terms: ['led bulb', 'bulb', 'بلب'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '💡',
    default_unit: 'pcs',
    canonicalName: 'LED Bulb',
    nameUrdu: 'ایل ای ڈی بلب',
    nameRomanUrdu: 'LED Bulb',
    categoryId: 'hardware',
    defaultUnit: 'pcs',
  },

  // ==========================================
  // 20. STATIONERY (اسٹیشنری)
  // ==========================================
  {
    id: 'stat_notebook',
    canonical_name: 'Notebook / Register',
    english_name: 'Notebook',
    urdu_name: 'رجسٹر / کاپی',
    roman_urdu_names: ['Notebook', 'Register', 'Copy'],
    aliases: [
      'notebook', 'register', 'copy', 'school copy', 'writing pad',
      'kapi', 'rajister',
      'رجسٹر', 'کاپی', 'نوٹ بک',
    ],
    common_misspellings: ['kapi', 'rajister'],
    category_id: 'stationery',
    subcategory_id: 'stat_notebooks',
    searchable_terms: ['notebook', 'register', 'copy', 'رجسٹر', 'کاپی'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '📓',
    default_unit: 'pcs',
    canonicalName: 'Notebook',
    nameUrdu: 'رجسٹر',
    nameRomanUrdu: 'Register',
    categoryId: 'stationery',
    defaultUnit: 'pcs',
  },
  {
    id: 'stat_ballpoint_pen',
    canonical_name: 'Ballpoint Pen',
    english_name: 'Ballpoint Pen',
    urdu_name: 'بال پوائنٹ پین',
    roman_urdu_names: ['Pen', 'Ballpoint', 'Ball Point'],
    aliases: [
      'pen', 'ballpoint', 'ball point', 'blue pen', 'black pen', 'piano pen',
      'pain',
      'پین', 'بال پوائنٹ',
    ],
    common_misspellings: ['pain', 'ballpen'],
    category_id: 'stationery',
    subcategory_id: 'stat_writing',
    searchable_terms: ['pen', 'ballpoint', 'پین'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🖊️',
    default_unit: 'pcs',
    canonicalName: 'Ballpoint Pen',
    nameUrdu: 'بال پوائنٹ پین',
    nameRomanUrdu: 'Pen',
    categoryId: 'stationery',
    defaultUnit: 'pcs',
  },

  // ==========================================
  // 21. CLOTHING (کپڑے اور ملبوسات)
  // ==========================================
  {
    id: 'cloth_socks',
    canonical_name: 'Socks',
    english_name: 'Socks',
    urdu_name: 'جرابیں',
    roman_urdu_names: ['Jurabein', 'Socks', 'Mojay'],
    aliases: [
      'socks', 'sock', 'cotton socks',
      'jurabein', 'jurab', 'mojay', 'moja',
      'جرابیں', 'موزے',
    ],
    common_misspellings: ['jurab', 'mojay'],
    category_id: 'clothing',
    subcategory_id: 'cloth_basic',
    searchable_terms: ['socks', 'jurabein', 'mojay', 'جرابیں'],
    active: true,
    created_at: NOW,
    updated_at: NOW,
    emoji: '🧦',
    default_unit: 'pair',
    canonicalName: 'Socks',
    nameUrdu: 'جرابیں',
    nameRomanUrdu: 'Jurabein',
    categoryId: 'clothing',
    defaultUnit: 'pair',
  },
];
